services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin1115
      POSTGRES_DB: barberia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: barberia_pgadmin_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@barberia.com
      PGADMIN_DEFAULT_PASSWORD: Admin1115
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    container_name: barberia_backend_dev
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/barberia_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Admin1115
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: