services:
  # -------------------------------------------------------------
  # Componente: Backend DEV (Hot Reload)
  # -------------------------------------------------------------
  backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: flowbox_backend_dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-hidden-breeze-atsz4x4s.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=${NEON_DB_PASSWORD}  # Sigue leyendo de tu .env local
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    ports:
      - "8080:8080"
    volumes:
      # Estos volúmenes son el "espejo" entre tu PC y Docker
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml