services:
# -------------------------------------------------------------
  # Componente: Backend (API REST - Spring Boot)
  # -------------------------------------------------------------
  backend:
    build:
      context: .              # Ambos archivos están en la raíz del proyecto
      dockerfile: dockerfile  # Nombre del archivo 100% en minúsculas
    container_name: flowbox_backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-hidden-breeze-atsz4x4s.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=${NEON_DB_PASSWORD}  # Docker leerá esto automáticamente de tu archivo .env local
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    ports:
      - "8080:8080"           # Puerto para acceder a tu API REST desde afuera
    networks:
      - flowbox-network       # Conectado a la red interna para el futuro frontend

  # -------------------------------------------------------------
  # [PREPARADO A FUTURO] Componente: Frontend
  # -------------------------------------------------------------
  # Cuando crees tu frontend, solo debes descomentar las líneas de abajo:
  # frontend:
  #   build:
  #     context: ./frontend  # O la carpeta donde decidas ponerlo
  #     dockerfile: dockerfile
  #   container_name: flowbox_frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"        # O el puerto que use tu framework (React, Angular, Next, etc.)
  #   networks:
  #     - flowbox-network

# Red interna de Docker para que los componentes se comuniquen de forma segura
networks:
  flowbox-network:
    driver: bridge