spring.application.name=flowbox-backend
# ===============================
# CONEXIÓN A BASE DE DATOS (NEON CLOUD)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-hidden-breeze-atsz4x4s.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${NEON_DB_PASSWORD:contrasenia_generica}
spring.datasource.driver-class-name=org.postgresql.Driver

# Mantenemos esto para que Spring cree las tablas en Neon automáticamente
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# "validate" asegura que Java solo lea y escriba registros.
# Si tu código Java no coincide con las tablas de pgAdmin, Spring Boot tirará un error y no arrancará.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ===============================
# SERVIDOR
# ===============================
server.port=8080